### ISSUE TITLE
Bold support

### ISSUE THREAD

**Issue by alexozer** [subnixr/minimal#11]
I'm used to a bold prompt and feel it could help stand out among other contents. Maybe adding a bold option to the info functions would do the trick? Maybe supporting arbitrary formatters would be better, but that might be more complex to use than just writing components yourself.

**Comment by subnixr** [comment]
Sorry for the late response, but between festivities and exams I'll be busy for the next month.

Unfortunately, this problem is not solved by simply print the correct sequence for bold before every component, as it will be overriden by the next ANSI sequence.
A bold flag for function is an "ugly" solution, in fact a formatter is a cleaner and more extensible apporach but I fear it's a bit of over-engineering. I'll think about this.

For the moment, I suggest to copy-paste the components you want in bold into your rc files, then tweak them. For example:

```
function my_mnml_keymap {
    local kmstat="$MNML_INSERT_CHAR"
    [ "$KEYMAP" = 'vicmd' ] && kmstat="$MNML_NORMAL_CHAR"
    # "%{\e[1m%} for bold
    echo -n "%{\e[1m%}$kmstat"
}

MNML_PROMPT=(mnml_ssh mnml_pyenv mnml_status my_mnml_keymap)
```

**Comment by alexozer** [comment]
That's fine, it's not a huge deal, and I understand.
